services:
  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: openfabric-gateway
    volumes:
      - ..:/opt/src
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
